# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command


#update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.46.1"

# This value helps us track success metrics for Fastfiles
# we automatically generate. Feel free to remove this line
# once you get things running smoothly!
generated_fastfile_id "60ebab3e-2cb9-465c-9f11-cba10543d5c8"

default_platform :android

# Fastfile actions accept additional configuration, but
# don't worry, fastlane will prompt you for required
# info which you can add here later
lane :beta do
    if "stable" != git_branch
        UI.user_error!("Please switch to stable branch when creating the build.")
    else
        #first we don't have uncommited changes
        ensure_git_status_clean

        #pull latest version, "protiv uroka"
        git_pull

        # increment the build version code and name
        increment_android_version_code(path: "app/build.gradle")
        increment_android_version_name(path: "app/build.gradle", type: "patch") #todo pass this param maybe?

        #get changelog from commits
        changelog_from_git_commits

        # build the release variant
        gradle(task: "assembleRelease")

        # upload to Beta by Crashlytics
        crashlytics(
            api_token: "31bbb01b57fcc2466eafe396865bc324f8a56f8b",
            build_secret: "6646557059011dacaae43c6077a37c8fe09cfbc249adfcb75ec7051920a3a00a"
          )

        slack(
            slack_url: "https://hooks.slack.com/services/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",
            message: "New version of Coligo messenger added to Fabric Beta",
            username: "Coligo Bot",
            channel: "#native",
            icon_url: "http://i.imgur.com/1nN9U2r.png",
            default_payloads: [],
            payload: {
                "Built at" => Time.new.to_s,
                "Version code" => lane_context[SharedValues::ANDROID_VERSION_CODE],
                "Version name" => lane_context[SharedValues::ANDROID_VERSION_NAME]
            },
            attachment_properties:{
                thumb_url: "http://i.imgur.com/1nN9U2r.png"
            }
        )

        #after everything, commit
        git_commit(path: "app/build.gradle", message: "Bumped app version to " + lane_context[SharedValues::ANDROID_VERSION_NAME])

        #git new tag
        add_git_tag(
          tag: "v" + [SharedValues::ANDROID_VERSION_NAME]
        )

        #push to stable
        push_to_git_remote
    end


end